### ISSUE TITLE
BER does not render texture for a simple block

### ISSUE THREAD

**Issue by uiytt** [FabricMC/fabric#1048]
So I have this BER only supposed to render a block (in general it also do other things, this is why I'm using a BER). 
And I'm adding a texture to it, but no matter what I do, It only show a black cube instead of the texture.
I've trying asking to people in the discord, but nobody found anything wrong.

I've created a minimum reproducible example in 1.16.2 with the only thing you need to reproduce the bug.
Here it is : [https://github.com/uiytt/ErrorMod/tree/master/src/main/java/net/fabricmc/example](https://github.com/uiytt/ErrorMod/tree/master/src/main/java/net/fabricmc/example) 

Does anybody has any idea as to why the texture doesn't render at all ?

**Comment by ghost** [comment]
I'm pretty sure the issue is that you aren't registering the texture on the client side. What you want is [ClientSpriteRegistryCallback](https://github.com/FabricMC/fabric/blob/1.16/fabric-textures-v0/src/main/java/net/fabricmc/fabric/api/event/client/ClientSpriteRegistryCallback.java). That being said, the fabric api GitHub repository is not the right place to be asking development questions about your own mod. In the future, if you'd like help with mod development, please join the [fabric discord](https://discord.gg/v6v4pMv) and post your questions in either the #mod-dev-1 or #mod-dev-2 channels, and we'll be glad to help.

**Comment by uiytt** [comment]
Thanks.
For this question, I asked during several days if anyone know why this didn't work on #mod-dev-1 and 2, re-posting when my message got lost.
After four days, nobody found why it was wrong, and so I assumed I was having some sort of bug...
So sorry and thanks
