### ISSUE TITLE
Crash con Fabric 1.16.5 client

### ISSUE THREAD

**Issue by JoakoLP** [FabricMC/fabric#1414]
Today i started trying to make a Fabric server, i allways used Forge. The server ran well, but the client with the same mods crashed.
[Crash Log](https://pastebin.com/wnxX14vp)

**Comment by frqnny** [comment]
I would go around and check that every mod is updated and then retry-it seems a mod's library, called Artiface, is a little broken. It does not crash on servers because it is only applying the broken feature that crashes on the client.

**Comment by JoakoLP** [comment]
And how can i know on which on my mods is that library working?
![image](https://user-images.githubusercontent.com/82276442/114285896-07363480-9a31-11eb-822f-65ed0d95c401.png)

**Comment by frqnny** [comment]
I'm not sure. you can check that all those mods are updated, and then what I would do is (because it is a startup crash) test with half of the mods. If it crashes, you know what half of the mod folder has the bad mod. And you can keep going and halving until you are able to narrow down the problematic mod. Artiface is a library that generates resources at runtime, so I'd take all mods that don't add any blocks or items out tbh.

**Comment by JoakoLP** [comment]
I think i solved that, but now it doesn't load. It keeps stucked on this.
Occasionally it shows a menu but it cames back to the loading screen instantly.
https://user-images.githubusercontent.com/82276442/114291204-dfa89180-9a5b-11eb-8653-c510c15612a6.mp4

**Comment by frqnny** [comment]
I'd try removing Optifine and optifabric as they tend to break a lot. That's a resourcepack loading error.

**Comment by JoakoLP** [comment]
Yes, i did that and it worked. Also I added sodium and it works too much better than optifine. I'm new on fabric.

**Comment by frqnny** [comment]
Welcome to Fabric! Glad you were able to fix your issue.
