### ISSUE TITLE
`FabricBlockSettings.copyOf` doesn't copy `jumpVelocityMultiplier`

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [FabricMC/fabric#1873]
Doing `FabricBlockSettings.copyOf(Blocks.HONEY_BLOCK)` makes it so the block these settings are used on still has normal jump height on top of it. Adding `.jumpVelocityMultiplier(0.5f)` manually fixes it, however this implies that `jumpVelocityMultiplier` is not copied.

**Comment by haykam821** [comment]
Keep in mind that the vanilla implementation does not copy `jumpVelocityModifier` either, alongside other fields such as the various context predicates, likely because no vanilla block requires them to be copied. I would change the Fabric API method to copy these fields, but also add a note that additional fields may be copied compared to vanilla's implementation.

**Comment by TheDrawingCoder-Gamer** [comment]
That's probably an oversight. Walking speed carries over thus it follows that jump height should carry over.
