### ISSUE TITLE
Having trouble with fabric not working : Invalid Java Runtime Configuration Issue, exit code 1

### ISSUE THREAD

**Issue by JulianPanda** [FabricMC/fabric#2007]
I've tried uninstalling and reinstalling, fabric and all my mods, including minecraft itself uninstalling and reinstalling it, but to no avail i keep having the pop up, Game Crashed, invalid java runtime configuration, check any custom configuration settings exit code 1. I've googled a bunch of stuff but I'm at a loss, regular minecraft and optifine work, but I'm at a loss with this. :(
![invalid java runtime configuration exit code 1](https://user-images.githubusercontent.com/99911053/154549876-2fdc723d-9278-463d-9847-103d35b044bb.png)

**Comment by warjort** [comment]
The error says the parameters you are passing to the java runtime are not correct.

Since you don't post any information about that (or any information about how you are loading minecraft) it is hard to say where they are wrong.

The fabric api does not really support running with Optifine, it is closed source and does many incompatible changes to minecraft.
If you want help trying to run fabric with optifine try here:
https://github.com/Chocohead/OptiFabric/issues

Alternatively, try using other mods that do the same things as optifine:
https://lambdaurora.dev/optifine_alternatives/

**Comment by warjort** [comment]
> The error says the parameters you are passing to the java runtime are not correct.

You could also look for a log/latest.log in your minecraft folder

**Comment by JulianPanda** [comment]
ah sorry i sort of figured it out. I meant using optifine and fabric separately, optifine worked but fabric didnt. But in the end it seems to be an issue with cloth's config api and regular api and architectury mod with roughly enough items. Taking those 4 mods out fixed everything after a lot of trial and error. But here is also the latest log if that helps
[latest.log](https://github.com/FabricMC/fabric/files/8091645/latest.log)

**Comment by warjort** [comment]
> fabricloader 0.13.2
> optifabric 1.12.10

https://github.com/Chocohead/OptiFabric/issues/605

Looks like a known issue to me?

**Comment by ghost** [comment]
Known issue, Fabric Loader 0.13 does not support OptiFabric, downgrade Architectuary and Cloth Config to a version compatible with 0.12 and it'll work. 

EDIT: Its an Optifabric issue, not Fabric itself.
