### ISSUE TITLE
servers not available from ukraine

### ISSUE THREAD

**Issue by iocmet** [FabricMC/fabric#2053]
> [DownloaderThread] Failed to download: https://maven.fabricmc.net/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
java.io.IOException: not a first attempt; failed
	at ru.turikhay.tlauncher.repository.RepositoryProxy$ProxyRepo.get(RepositoryProxy.java:98)
	at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:180)
	at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:110)

**Comment by warjort** [comment]
> at ru.turikhay.tlauncher.downloader.DownloaderThread.run

Cracked launchers are not supported. You will have to ask them to fix whatever the problem is.
See https://fabricmc.net/use/installer/ for supported options.

**Comment by iocmet** [comment]
servers are not available from ukraine

**Comment by iocmet** [comment]
I can't download from the site

**Comment by iocmet** [comment]
connection is reset

**Comment by modmuss50** [comment]
We use cloudflare in front of some of our domains, and due to the ongoing issues I expect they have increased their security checks for certain areas.

The security levels we use are already very low, however I have made a change that may help you guys out. So hopefully it will work now.

Stay safe and let me know if you have any other issues.

**Comment by iocmet** [comment]
ok thanks
