### ISSUE TITLE
my game keeps crashing when i try to load fabric

### ISSUE THREAD

**Issue by vzixx** [FabricMC/fabric#2056]
![Capture](https://user-images.githubusercontent.com/101080564/157134565-d62577b2-1135-40da-95cb-abd9b49d2fd6.PNG)

**Comment by warjort** [comment]
Post your log/latest.log

**Comment by warjort** [comment]
class_3304 is the ReloadableResourceManagerImpl
It says it cannot load the class due to a mixin error which the log might provide more information about.
This is usually because 
* you are trying to use a mod for the wrong version of minecraft
* sometimes you have 2 mods interfering with each other
* the mod is just broken

It is very unlikely to be a fabric api issue, something you can check by trying to load minecraft with just the fabric api.

**Comment by vzixx** [comment]
@warjort i was trying to load wurst but i have the correct version idk what could be the issue

**Comment by warjort** [comment]
Post your log/latest.log

Or start with only the fabric api and add mods one by one until you find the problem mod.

**Comment by deirn** [comment]
Cheat mod is not supported here.
