### ISSUE TITLE
Fabric API versions marked for 1.18.1 crash during initialization

### ISSUE THREAD

**Issue by alittlewarlord** [FabricMC/fabric#2057]
Hello! I was having some issues building a modpack on my own, and in the bugfixing, I decided to try out a completely bare instance of fabric, with just fabric itself and the two latest versions of the fabric-api jar (0.46.4+1.18 and 0.46.6+1.18 at the time of opening). The game crashed during initialization, and I figured this would be a bug you want to know about.

Here is a paste.ee of the log recorded with [api-0.46.4+1.18](https://paste.ee/p/nenaZ)
And one of the paste.ee of the log recorded with [api-0.46.6+1.18](https://paste.ee/p/ik8On)

For whatever weird reason, this wasn't affecting a different, established instance of a 1.18.1 game with api-0.46.4+1.18 until yesterday, either. I have noticed extremely similar error messages on other opened issues, but a lot of the posters don't seem to have found the same root cause.

If you need anything else from me, let me know! I know maintaining things like this wonderful project is stressful, and I'll do what I can to help.

**Comment by warjort** [comment]
````
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: glfw.dll
	at org.lwjgl.system.Library.loadNative(Library.java:299)
	at org.lwjgl.system.Library.loadNative(Library.java:205)
````

This is not a fabric api issue.

The error says java can't load the opengl native libraries used by minecraft.

In your case this is the responsbility of multimc since that is the launcher you are using.

But I believe this is usually a file system problem  where the folder used to store the dlls does not have the correct permissions
or the user starting minecraft doesn't have permissions to some files/folders.
The error can also happen if the path name contains non-standard characters, but that doesn't look to be an issue for you?

In your case the folder is
````
Native path:
  C:/Users/me/Documents/MultiMC/instances/bugfixing/natives
````

If you think everything is correct, ask on the multimc discord or issues page.

**Comment by alittlewarlord** [comment]
Thank you so much! I'm bringing this to them now, thank you for catching what I couldn't in the logs!
