### ISSUE TITLE
MipMap-Levels doesn't work in Fabric.

### ISSUE THREAD

**Issue by Gbergz** [FabricMC/fabric#209]
Title^

MipMap Levels does not appear to be working in Fabric. It's been buggin' me for awhile might aswell report it see if it can be fixed. <3

![mipmap pic](https://user-images.githubusercontent.com/26634554/58352117-e54a5d80-7e6a-11e9-8bdb-c04fe4588b84.PNG)

**Comment by asiekierka** [comment]
What API version?

**Comment by grondag** [comment]
Also, any mods installed?

**Comment by Gbergz** [comment]
Yes mods are installed. I'm playing with All of Fabric Modpack v2.3.0. 
Fabric API version is: fabric-api-0.3.0-pre+build.157a.jar

**Comment by grondag** [comment]
MipMap appears to be working fine in a Fabric-only environment.  It's very likely this is caused by one of the mods in that pack. Which means the Fabric team can't fix it. 

It would be helpful to identify the mod causing this and report the problem to the author of that mod.  If you are using something like MultiMC it doesn't necessarily take that long to identify the mod.  Here's a way you can do it:

Disable half the mods (top half, bottom half, doesn't matter).
START A NEW WORLD - otherwise blocks will go missing in your game world.

If the problem is gone: the offending mod is one of the disabled mods. Disable the enabled modes and enable half of the mods that were disabled.

If the problem is still there, the offending mod is one of the enabled mods. Disable half the enabled mods.

Repeat the process, each time cutting the number of mods enabled in half, until you know which mod is causing the problem.  AoF has about 180 mods, so you'd need about 7 passes.

Alternatively, you can guess the culprit and try disabling mods a few at a time.  The mod causing the problem is likely to be rendering-related or have blocks with fancy rendering, but it may not be!  Minecraft is a complex beast and surprising interactions happen all the time.

**Comment by doctor4t** [comment]
@Gbergz Do you have the Illuminations mod installed currently?

**Comment by Gbergz** [comment]
So i've tracked down the mod that is causing it and it is the mod Illuminations. Removing it brings back functionality to Mip-map levels.

**Comment by Gbergz** [comment]
> @Gbergz Do you have the Illuminations mod installed currently?

Yes, and it was that mod causing it to not work.

**Comment by grondag** [comment]
I see you already logged the issue on the Illuminations issue tracker. Thank you for doing that. Looks like this issue can be closed now.
