### ISSUE TITLE
[22w13oneBlockAtATime] Generic Item Block is not rendered correctly

### ISSUE THREAD

**Issue by Flamarine** [FabricMC/fabric#2106]
I don't know whether bugs in such af snapspots will be fixed or not, but I think an issue is required...

![2022-04-03_18 16 41](https://user-images.githubusercontent.com/62203463/161422800-00d36708-8a84-4a53-b009-5f924466d3e0.png)
![2022-04-03_18 16 51](https://user-images.githubusercontent.com/62203463/161422803-5912a605-34d2-4e4e-880c-abb956a4b0be.png)

Only have Fabric API (0.48.1+22w13oneblockatatime) installed.

As you can see, generic item blocks are rendered as white carpets, while they are intended to be rendered as different items.

**Comment by sudofox** [comment]
I'm having the same issue. This snapshot is so fun, I would love to be able to mod it a little bit for an even cooler experience.

I think the April Fools snapshots should get extra consideration since they're more memorable "special editions" released through the snapshot channel.

FWIW white carpet is the default appearance for item ID 0

**Comment by lasagnda** [comment]
I am also having this issue, although I may have found the root of the problem. 

Since the Fabric API is made for mod resources and whatnot, it creates it's own resources for mods so their textures may load correctly.

The only issue with that, is that the resources cause our items to lose their texture IDs. Removing the resources may be the only solution to the problem.
![image](https://user-images.githubusercontent.com/103087857/161885693-7c2d34f8-4067-4272-9545-e06ff87f151c.png)

If anyone has more insight on this topic please share!

**Comment by dbrighthd** [comment]
I'm having the same issue, I hope it will get resolved

**Comment by Technici4n** [comment]
I don't think this will ever be fixed.
