### ISSUE TITLE
Fabric mods using json for their worldgen isn't loading in the json files on 1.19 snapshots.

### ISSUE THREAD

**Issue by ExDrill** [FabricMC/fabric#2225]
The rundown is:
I recently decided to port my mod into the snapshots, and my mod so happens to use json for it's world generation (like structures, features, biome settings, etc). But whenever launching a world, it doesn't load up those json files because the biomes are featureless, locating the structure doesn't work. I'm not really sure if this is either a Minecraft thing or a Fabric thing, but it's worth reporting.

Additional Info:
- On the world creation screen, you can work around the issue by going into the datapack screen and closing out of it so the game verifies it, with that, the world will now load the worldgen folder just fine.
- Worlds loaded from 1.18 will still continue to work just fine

**Comment by ExDrill** [comment]
I just found something else about this issue, if I go onto the datapack selection screen when creating a new world, and leave it, the game will verify that the datapacks are correct, and will now properly load the worldgen folder once the world created.

**Comment by apple502j** [comment]
For people reporting the bugs: Please attach a **minimum reproduction** data pack (so that I can test the fixes). Ideally it should require as little resource to load as possible because my laptop is potato (customized void world would be nice.)

Current research result on dedicated, pre3:

- FRL loads the data pack under mod folder just fine, before immutablizing the DRM
- Dynamic registry `chat_type` gets loaded to the DRM from the mod bundled data pack

**Comment by apple502j** [comment]
Also, if you can, let me know if it works if you move any registry operations to EndDynamicRegistrySetupCallback provided by https://github.com/frqnny/structurized mod (@frqnny maintains it)

**Comment by Starmute** [comment]
Seems this issue is not completely resolved? In 1.19 loading a dimension via datapack (packaged in a fabric mod) is not functioning properly

**Comment by Starmute** [comment]
[Terralith_v2.3.2_fabric_test_build.jar.zip](https://github.com/FabricMC/fabric/files/8883117/Terralith_v2.3.2_fabric_test_build.jar.zip)
