### ISSUE TITLE
Fabric 1.19 (0.14.7-1.19) Literally burning my computer

### ISSUE THREAD

**Issue by RihzyStudent** [FabricMC/fabric#2313]
While starting up minecraft 1.19, cpu temps reach up to 112 degrees before my pc shuts down. This does not happen with lunar, normal mc or forge.

**Comment by warjort** [comment]
Pretty sure this is not a fabric bug.
Sounds like one of your mods is looping (100% cpu) due to a bug or misconfiguration?

To find out which mod is looping you can post your logs/latest.log to see if it has any clues.

But likely that won't show anything useful, so you will need to generate a thread dump:
https://www.baeldung.com/java-thread-dump
which will probably mean installing a java jdk to get the tools.

Alternatively, uninstall all your mods and then add them back individually until you find the problem mod.

**Comment by warjort** [comment]
You probably also want to check your cpu fan and/or any control parameters you have configured since it doesn't seem to working properly? The shutdown because overheating should only be a failsafe.

**Comment by RihzyStudent** [comment]
I ran fabric without any mods so can't be a mod issue.
The thing is fabric doesn't crash it just keeps getting up to 100 degrees, 112 until finally my pc gives up. Attaching the log anyways

[latest.log](https://github.com/FabricMC/fabric/files/8886194/latest.log)
 

> You probably also want to check your cpu fan and/or any control parameters you have configured since it doesn't seem to working properly? The shutdown because overheating should only be a failsafe.

Yea, I checked hwinfo and nothing seems off with about 60 degrees at idle (normal in summers)

**Comment by warjort** [comment]
Not only do you not have any mods, you don't have the fabric api installed.
Its a bit strange reporting a bug against a project you are not using. :-)

You do have the fabric loader installed, https://github.com/FabricMC/fabric-loader
but without any mods, it doesn't do very much except change the classloader.
Everything else will be vanilla minecraft.

The log shows nothing except a shutdown 4 seconds after it loads the resource packs.
````
[21:23:39] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:23:43] [Render thread/INFO]: Stopping!
````

I do see this message from vanilla
````[21:23:28] [main/INFO]: Building optimized datafixer````
which doesn't have a corresponding end log statement, e.g.
````[09:13:27] [Worker-Bootstrap-7/INFO] (Minecraft) 4256 Datafixer optimizations took 46116 milliseconds````
so that might be a clue the problem is that processing? But that is vanilla minecraft not fabric.
There is a mod that defers this processing: https://www.curseforge.com/minecraft/mc-mods/lazydfu
if you want to try it. But it is just a guess.

A java thread dump is what is really needed to see what is going on.
But if you only have 4 seconds to do it this might be hard to capture?

**Comment by warjort** [comment]
It does seem strange that the cpu will overheat in just 4 seconds doing whatever it is doing after the resource pack load. 
This does lend some weight to it being that background dfu optimization which runs for quite a while during the bootstrap?

**Comment by Sollace** [comment]
Seems like the "Building optimized datafixer" is pretty resource intensive. Even with my beefy system (16 cores and 32GB of RAM), it still takes unusually long:

    [m[34m[18:29:00][m [32m[Worker-Bootstrap-10/INFO][m [36m(Minecraft)[m [0m4256 Datafixer optimizations took 35247 milliseconds

**Comment by RihzyStudent** [comment]
> Not only do you not have any mods, you don't have the fabric api installed. Its a bit strange reporting a bug against a project you are not using. :-)
> 
> You do have the fabric loader installed, https://github.com/FabricMC/fabric-loader but without any mods, it doesn't do very much except change the classloader. Everything else will be vanilla minecraft.
> 
> The log shows nothing except a shutdown 4 seconds after it loads the resource packs.
> 
> ```
> [21:23:39] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
> [21:23:43] [Render thread/INFO]: Stopping!
> ```
> 
> I do see this message from vanilla `[21:23:28] [main/INFO]: Building optimized datafixer` which doesn't have a corresponding end log statement, e.g. `[09:13:27] [Worker-Bootstrap-7/INFO] (Minecraft) 4256 Datafixer optimizations took 46116 milliseconds` so that might be a clue the problem is that processing? But that is vanilla minecraft not fabric. There is a mod that defers this processing: https://www.curseforge.com/minecraft/mc-mods/lazydfu if you want to try it. But it is just a guess.
> 
> A java thread dump is what is really needed to see what is going on. But if you only have 4 seconds to do it this might be hard to capture?

Hm, do you think this is a hw optimization issue or something related to my system. Ill try booting up a linux partition to check if the same thing happens there. Also my bad i shouldve posted this in minecraft bugs but i realised that a literal second after posting it 😅 sorry!

**Comment by immortius** [comment]
A CPU shouldn't overheat and shut down even at 100% CPU if installed properly, so I would check the CPU cooler is working and probably consider reseating the cooler (take it off, clean off previous thermal paste, apply fresh and reinstall cooler). I had a similar issue in the past that was caused by a bubble in the thermal paste.
