### ISSUE TITLE
Custom dimensions not saving/loading in fabric 1.19

### ISSUE THREAD

**Issue by immortius** [FabricMC/fabric#2316]
Encountered this issue with my mod https://github.com/immortius/chunkbychunk/issues/10 . While chunks from custom dimensions (added programmatically) seem to save correctly, the existence of the custom dimensions does not serialize/deserialize with fabric in 1.19 (specifically the LevelStems/Levels). They do serialize/deserialize correctly with forge. I've worked around this by recreating them programmatically when loading, but this wasn't necessary in 1.18/1.17.

This is a deviation from previous behaviour, but I don't know if it is intended or a side effect of changes to minecraft rather than fabric... or potentially I've been setting up dimensions wrong the whole time 🤷

**Comment by apple502j** [comment]
@immortius Fabric intentionally strips the dimension data from level.dat because people have reported this causes issues when removing a dimension mod. According to them it regenerates on launch - however I am unsure if they are correct.

If you rely on custom dimension's `WorldGenSettings` being saved in level.dat file, that would cause an issue.

**Comment by immortius** [comment]
My mechanism for adding the dimensions is probably non-standard - since it isn't using datapacks. So if the removal of dimension data is intentional then I'ld say it is working as intended.
