### ISSUE TITLE
ClientPlayerEntity#dropItem() not dropping anything

### ISSUE THREAD

**Issue by INeedAwesome** [FabricMC/fabric#2331]
Hello! 
Im trying to make a mod (mostly for myself) where I can throw all of my ender pearls out of my inventory when i press a button (U). 
I have noticed that ClientPlayerEntity#dropItem() does not work, and I want to know how I throw stuff out of the inventory. As I don't find a way. 
What's happening is that my arm swings but that's it. What I expect it to do is drop the item like pressing the q button.

My mod is developed client side. [Github repo](https://github.com/INeedAwesome/Julkinen) and the [file](https://github.com/INeedAwesome/Julkinen/blob/1.19/src/main/java/site/gr8/mattis/ThrowEnderPearls.java) is available.
What am I doing wrong?

**Comment by warjort** [comment]
This area is for bug reports of the fabric api.
If you want help, please use the discussions tab or the fabric discord.

Anyway, at first glance:
https://github.com/INeedAwesome/Julkinen/blob/a7fcfcdba940e6364da4b7adde43ae239b6d7fc4/src/main/java/site/gr8/mattis/ThrowEnderPearls.java#L18
Shouldn't this be "Ender Pearl", not "ender pearl"?
It would be better to use ````stack.getItem() == Items.ENDER_PEARL```` because different languages.

**Comment by warjort** [comment]
I also think dropItem() is probably the wrong method on the client. The client method should be only used in response to events happening on the server when dropItem() is invoked on the ServerPlayerEntity?
Compare with the "q key" method that uses dropSelectedItem() which actually sends messages to the server, i.e. it initiates the event.
