### ISSUE TITLE
Fix for MC-243458

### ISSUE THREAD

**Issue by TheButterbrotMan** [FabricMC/fabric#2368]
Implenting a fix for https://bugs.mojang.com/browse/MC-243458 into Fabric.

I think this fix is very important because it is a general problem for modding. The bug causes that some custom structures and custom world generation is applied only after deleting /region files. This is very difficult to solve especially for modpack authors because not all players are able to do this.

I know that this was fixed some time ago in Forge, however I believe that this bug is still present in Fabric.

**Comment by modmuss50** [comment]
We already fix: https://bugs.mojang.com/browse/MC-195468 is this not the same bug? Can you try again on the latest fabric api released yesterday as it contained a number of fixes around this kind of issue.

**Comment by TheButterbrotMan** [comment]
Would be awesome. Ill check this!

**Comment by apple502j** [comment]
This should be fixed by #2261 and #2345.

Note: [MC-195468](https://bugs.mojang.com/browse/MC-195468), a bug in `server.properties` file, has never affected mods or been fixed by us. The fixes we have in Resource Loader and Dimension API are for [MC-243458](https://bugs.mojang.com/browse/MC-243458).

**Comment by apple502j** [comment]
Closing, as I believe it was fixed by the two PRs I mentioned. @TheButterbrotMan If this is still not fixed, please comment here.
