### ISSUE TITLE
Page turning buttons in creative inventory don't appear in 22w45a

### ISSUE THREAD

**Issue by Iunius118** [FabricMC/fabric#2652]
- Fabric version: 0.66.1+1.19.3

I'm trying to add an item group, but the page turning buttons don't appear in the creative inventory and I can't see the tab I added.

```java
FabricItemGroup.builder(new Identifier("modid", "test_group_0"))
		.displayName(Text.literal("Test Item Group: 0"))
		.icon(() -> new ItemStack(Registries.BLOCK.get(1)))
		.entries((enabledFeatures, entries, operatorEnabled) -> {
			entries.add(new ItemStack(Registries.ITEM.get(1)));
		})
		.build();
```

![Screenshot 1: one item group](https://user-images.githubusercontent.com/18502177/201482594-bbd0ac24-ac44-4348-a74c-9091de8f1d43.png)

Curiously, when two item groups are added, the buttons show up.

```java
for (int i = 0; i < 2; i++) {
	final int index = i + 1;
	FabricItemGroup.builder(new Identifier("modid", "test_group_" + i))
			.displayName(Text.literal("Test Item Group: " + i))
			.icon(() -> new ItemStack(Registries.BLOCK.get(index)))
			.entries((enabledFeatures, entries, operatorEnabled) -> {
				entries.add(new ItemStack(Registries.ITEM.get(index)));
			})
			.build();
}
```

![Screenshot 2: two item groups](https://user-images.githubusercontent.com/18502177/201482603-e234cab9-c811-48cf-aa28-8154917aacc6.png)

**Comment by haykam821** [comment]
It seems like the buttons are visible when there are more than 14 item groups:

https://github.com/FabricMC/fabric/blob/f84bf2d968da3b4f1251f072122cfd5c8090dfa9/fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java#L71-L74

In vanilla, the operator item group may not be present at all times. What happens if you make the operator item group visible? It seems like Fabric assumes that the operator item group is included in the item group list when determining whether another page is needed.

**Comment by Iunius118** [comment]
> What happens if you make the operator item group visible?

When `operatorItemsTab` in options.txt is set to true, the first page has 14 tabs and page turning buttons and I can see my tab on the second page..

![Screenshot 3](https://user-images.githubusercontent.com/18502177/201484826-0e5e4e7e-d78f-4525-92a5-9776258ddf6f.png)

As you said, these buttons only seem to work well in certain situations.

**Comment by modmuss50** [comment]
Fixed with https://github.com/FabricMC/fabric/pull/2653
