### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by MCrafterzz** [FabricMC/fabric#31]
Hey I'm new so I have some questions for this new modloader/api:
Is it the modding api that we all have been waiting for?
When forge catches up, will it still be updated?
Does it want to replace forge or just be an alternative?
Are there any tutorials how to do the basic stuff like blocks? I want to recreate my current mod for fabric.
How easy is it to upgrade my mod when changing Minecraft version? Do thinks break all the time or is it more like spigot that works across multiple versions?

Thanks.

**Comment by Prospector** [comment]
First off, I'd suggest joining our discord server to ask questions in: https://discord.gg/v6v4pMv

Secondly, I'll try to answer a few of them. 

It's probably not the API/mod loader you've been waiting for, Fabric is simply a fun little project for making mods in a different way to Forge. 

Fabric being updated doesn't depend on Forge, it really depends on the community behind fabric and the interest in it. 

Again, Fabric's role is really defined by the community. If everyone uses it, then it would technically replace forge. If no one uses it, then it's dead. If some people use it, then it's an alternative. It can really be whatever you want, but at least for the foreseeable future it really shouldn't be considered anything in relation to Forge because Forge isn't on 1.14 and there is no alternative to Fabric right now.

Best resource for mod development is the discord server. You can also watch McJty's introduction video that explains a bit of the very basics of Fabric modding.

Fabric is not a full abstraction layer like spigot. It'll break whenever mojang breaks something. Fabric API and Loader will do their best to maintain compatibility until it makes sense to break it.

**Comment by MCrafterzz** [comment]
Thanks. So it will probably break with every Mc version. Is there any plans to make it more abstract to prevent it?

**Comment by liach** [comment]
making it abstract will lead to loss of functionalities. Even spigot is not persistent across versions; many plugins use a general reflection hack that handles different minecraft (craftbukkit) versions in its plugin jar so that it appears it is cross-version compatible/
