### ISSUE TITLE
Define that `Storage#iterator` must be inside of a transaction if modification is expected.

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#3123]
See discussion at https://discord.com/channels/507304429255393322/566417932503089232/1118520686625968209.

**Comment by MattiDragon** [comment]
Wouldn't this reintroduce the issue with the comparator output calculatation? Read only views would solve this. If we do decide to go for them we need to decide if I they should expose `simulate*` methods. In my usecase it wouldn't actually be hard to implement because I could make my sorting only happen on committed transactions.

**Comment by Technici4n** [comment]
No because the comparator output calculation doesn't use extract. 😉
