### ISSUE TITLE
Kicked from Server whilst Connecting with Fabric API loaded

### ISSUE THREAD

**Issue by ampersandhd** [FabricMC/fabric#3149]
```
Internal Exception:
io.netty.handler.codec.DecoderException:
java.lang.RuntineException:
Attempted to register ID
ResourceKey[minecraft:damage type / minecraft:outside border] at different raw IDs (30, 44)!
If you're trying to override an item, use .set() not .register()!
```

Players with Minecraft 1.20.1, Fabric Loader 0.14.21 and Fabric API 0.83/0.84.0 have this error. 
Players with Fabric Loader 0.14.21 and Fabric API 0.83.0 on 1.19.4 have no error. 
Players without Fabric API have no errors.

Server is on Paper 1.20.1. So the Error is in combination of Minecraft 1.20.1 and Fabric API only.
Any ideas? Could this be caused by a mod, plugin or fabric itself?

**Comment by Technici4n** [comment]
Can you try with the same client configuration, and a vanilla server?

**Comment by ampersandhd** [comment]
Works Fine. Also Works with Paper and about 20 Plugins.

**Comment by Technici4n** [comment]
By "same client configuration" I mean Fabric API and Minecraft 1.20.1. Does that work fine in all cases?

**Comment by modmuss50** [comment]
I just tested with a Paper server (no plugins) and Fabric API 1.20.1 and everything seems to be ok 🤔 

<img width="1912" alt="Screenshot 2023-06-26 at 13 14 28" src="https://github.com/FabricMC/fabric/assets/4324090/d95c1979-6617-4f1f-80d0-c0921d45728b">

**Comment by ampersandhd** [comment]
Yes. But Where to search? Until 1.19.4 everything was fine and without Fabric api everything is Fine, too. 

Must be a Special plugin that interacts with the latest Fabric API. 

Where to investigate further? What does this Error mean?

Could the Error be BungeeCord side?

**Comment by modmuss50** [comment]
Have you got any datapacks? Or plugins that mess with the damage types?

**Comment by spiderkitten** [comment]
I seem to be having this (or a similar) issue connecting to a server. It was fine when I was on MC 1.20 though, it's only since updating to 1.20.1 and Fabric API 1.20.1 that it is crashing. 

Minecraft 1.20.1 and either of these both crash:    
fabric-api-0.83.0+1.20.1  
fabric-api-0.84.0+1.20.1  

Minecraft 1.20 and this one works:  
fabric-api-0.83.0+1.20  

Its fine in single player, its only when I try to connect to the server that it crashes. 
Here's my crash log: https://pastebin.com/VMTeW9YM

**Comment by ampersandhd** [comment]
We solved the issue by Updating Waterfall on the Bungee.
