### ISSUE TITLE
Can't import `EntityRendererFactory`

### ISSUE THREAD

**Issue by Soulsender** [FabricMC/fabric#3197]
I can't import `EntityRendererFactory`. I don't know why. I'm using Minecraft 1.20.1. I'm also using geckolib version 4.2 if that helps. 

This is the import statement:
```java
import net.minecraft.render.entity.EntityRendererFactory;
```
Help would be greatly appreciated, I can't find anything on this issue anywhere and it's driving me insane because it's the only problem in between me and spawning my modded entity.

![image](https://github.com/FabricMC/fabric/assets/83854400/b334e4ce-44f0-481d-9142-6600e47d67d2)

**Comment by Daomephsta** [comment]
The issue tracker is for *final* issue reports and feature requests, not general problems. For those, start a [Discussion](https://github.com/orgs/FabricMC/discussions), or visit the [Discord](https://discord.gg/v6v4pMv).

It's likely you're using split sources (both `src/main` and `src/client` exist), as that's a default now because it's recommended.
Client-only code such as entity renderers *must* be in `src/client`. `src/main` cannot access client-only code, to prevent accidental usage of client-only code on dedicated servers.

If you have further questions, as mentioned, start a discussion, or visit the Discord.

**Comment by Soulsender** [comment]
I resolved my issue, apologies for the issue posting, I just couldn't find any anything relating to my problem online. 

Posting my answer [here](https://www.reddit.com/r/fabricmc/comments/150xylw/cant_import_entityrendererfactory/) for people experiencing a similar issue.
