### ISSUE TITLE
Improved Info Wishlist

### ISSUE THREAD

**Issue by Darkhax** [FabricMC/fabric#32]
This issue is a wishlist of improved information about the game that I think Fabric should provide. 

- [ ] Version of the Fabric API printed to console. Currently no way to tell without looking at the jar or installing mod menu. 
- [ ] Error message when an invalid recipe is loaded. 

I am going to add more as I find them, and if other people have things they want they can put them in the comments and I can add them to this list too.

**Comment by SquidDev** [comment]
I wonder if it'd be better to log all mod versions as part of fabric-loader? It's the sort of information which would be useful to have in the logs, even if people aren't depending on Fabric API.

**Comment by darkhax** [comment]
Yes, info logging would likely need to be split up given how fabric is modular. I forgot about that while making this issue. As for the recipes, in my case I had a recipe where the output was `minecraft:vector_plate` instead of `darkutils:vector_plate` and it did not complain about the recipe being bad. It was a very standard recipe. [Here](https://github.com/Fabric-Mods/Dark-Utilities/blob/master/src/main/resources/data/darkutils/recipes/vector_plate.json) is the now working json file.

**Comment by UpcraftLP** [comment]
update: fabric loader prints all loaded mods to the console on startup, including fabric api (if present).

**Comment by ghost** [comment]
I think a year ago Upcraft gave an apt enough observation for this to get closed. In addition, improper vanilla recipes now also print warnings, and for mod developers making custom recipe types that burden should fall onto them to make sure their recipe is being de-serialized properly. All in all this seems like it's no longer a concern.
