### ISSUE TITLE
Instaling fabric API slightly changes the world generation

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#3366]
Feature (grass, trees etc.) generation changes when i install fabric API

video [link](https://drive.google.com/file/d/1Y5XLmh8ugr6wU_buA6sCdnee2PpOMB73/view?usp=sharing)

minecraft version: 1.20.1
fabric API version: 0.89.3 (latest for 06.10.23)
seed: 8182091268832203360
teleportation command: _/tp @s -1472.30 64.00 27999.85 12.04 -12.60_
clipboard hotkey: win + v

i spent an entire evening disabling my mods in modrinth app to find out which of 100+ of them causes this bug

pretty sure FAPI for 1.20.2 has this bug too

this is not MC-55596 because it happens only when installing FAPI
there are several (probably ~20) variants of feature placement but none of them is equal to vanilla

**Comment by AnOpenSauceDev** [comment]
Can replicate:
## Fabric API
![2023-10-07_16 41 35](https://github.com/FabricMC/fabric/assets/119765865/8e77180e-7518-46c8-89d5-ba5a7066ebbd)

## Vanilla

![2023-10-07_16 44 24](https://github.com/FabricMC/fabric/assets/119765865/9a6fb217-cd1f-4ac7-a8e5-813fb217ba1f)

**Comment by maityyy** [comment]
I received a similar bug in my mod, replacing many vanilla biome placed features. I thought it was my bug, but it turns out not. In fact, if you generate this seed on Fabric again, you will find that the worlds are slightly different from each other — that is, Fabric does not just change the worldgen, it randomizes it
