### ISSUE TITLE
Leather item tag for convention-tags-v2

### ISSUE THREAD

**Issue by dhyces** [FabricMC/fabric#3731]
Would be nice to have for mods that add "leathers" comparable to regular leather.

**Comment by TelepathicGrunt** [comment]
It’s in the Neo side already.
https://github.com/neoforged/NeoForge/blob/c36a5ea78012784398ef93ebf1faf0a6e6913c72/src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java#L135

 Forgot about fabric side but seems good for someone to PR to add it. I guess I skipped it over due to only finding one mod using a similar tag on fabric. But if more are gonna use it, let’s add it to fabric side to match neo
![IMG_0892](https://github.com/FabricMC/fabric/assets/40846040/c44327fd-8278-4191-8503-b941f3014c93)

would be c:leathers

**Comment by dhyces** [comment]
> It’s in the Neo side already.
> https://github.com/neoforged/NeoForge/blob/c36a5ea78012784398ef93ebf1faf0a6e6913c72/src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java#L135
> 
>  Forgot about fabric side but seems good for someone to PR to add it. I guess I skipped it over due to only finding one mod using a similar tag on fabric. But if more are gonna use it, let’s add it to fabric side to match neo
> ![IMG_0892](https://github.com/FabricMC/fabric/assets/40846040/c44327fd-8278-4191-8503-b941f3014c93)
> 
> would be c:leathers

It's `c:leather` in neo

**Comment by TelepathicGrunt** [comment]
As per the field name, it should be leathers. I’ll make issue report to Neo as nouns should be plural
