### ISSUE TITLE
Feature Request: Add the `c:foods/cheeses` tag and perhaps other general food ones

### ISSUE THREAD

**Issue by thomasglasser** [FabricMC/fabric#3771]
This would be helpful for baking mods or others that want to use general cheese or other foods in their implementation so they don't have to rely on their own mod tags

**Comment by Alexander01998** [comment]
Hey @thomasglasser,

So, I'm not a Fabric maintainer, but I think I can answer this one.

Adding `c:foods/cheeses` and other `c` tags for modded food into Fabric directly seems unlikely to happen. The idea behind the `c` tags is that Fabric itself only adds a few tags for vanilla content, and then anyone can build on top of that with more tags for modded content.

So, you're totally able to add the `c:foods/cheeses` tag in your own mod. Other mods and datapacks will be able to use your tag too. Just keep in mind to check if there are any existing cheese mods and what they named their `c` tags. This helps maintain consistency across different mods.

Hope this helps!

**Comment by sciwhiz12** [comment]
I would say, if there is a resource which is verifiably widespread in many mods and would benefit from being defined in a single place, we should be open to adding that as a `c` tag. (Notwithstanding the current idea that both NeoForge and Fabric are synchronized with the set of `c` tags.)

For example, before 1.17's introduction of the copper ingot in vanilla Minecraft, many tech mods add some form of copper metal to the game. In such cases, it would be prudent to consider adding such a tag for copper ingots, even though vanilla did not have it, because quite a lot of mods use it, and it would be beneficial for mods to agree on the definition and the associated tags (storage blocks, ore blocks, etc.)

On how we determine the threshold between a modded concept being essentially enshrined in `c` based on the criteria I gave is up for discussion, either generally or on a case-by-case basis (and is why we have this issue-making and discussion).

That being said, mods are free to make their own tags under `c`, aligning with the naming conventions they can see in the existing tags (or looking at other mods which add a similar or equivalent tag). Consistency is key to ensure different mods recognize the same tag (and don't differ on pluralization, or affixes, or whatnot).

**Comment by TelepathicGrunt** [comment]
@thomasglasser How many mods do you know are adding cheese items? If there's a ton, yeah I can see a c tag being added would be ideal and help other mods tag their cheese properly. If it is only like 2 mods, then it'll be better for you to add the tag yourself and directly ask the other two mods to add to the tag rather than the tag being in the modloader.

**Comment by thomasglasser** [comment]
I wouldn't consider candies or berries or cookies commonly added items but they're listed

**Comment by TelepathicGrunt** [comment]
Candies, berries, and cookies are actually pretty common. Like I found quite a number of mods with these items and a few trying to make tags for them a thing.

However, I don’t see the same for cheese which is why I was asking you if cheese was indeed common and I just didn’t see any

**Comment by thomasglasser** [comment]
I haven't personally seen them, so ig I'll make it myself and reopen this if I see a need in the future.
