### ISSUE TITLE
Model offset is ignored by Indigo in non-terrain block rendering

### ISSUE THREAD

**Issue by PepperCode1** [FabricMC/fabric#3798]
This is an extremely old bug. I cannot identify if it was present in the original FRAPI/Indigo changes since I am not familiar with 1.15 rendering code, but I am quite sure it affects all versions 1.16 and newer, at least.

I plan to submit a pull request soon to fix this.

**Comment by PepperCode1** [comment]
It looks like model offsets for terrain rendering were also broken at some point but then fixed by [this pull request](https://github.com/FabricMC/fabric/pull/480). I assume offsets for non-terrain rendering have been broken since then as well, but no one noticed until now.

**Comment by peow** [comment]
this problem doesn't seem to have been solved yet
these 2 Pull Requests (https://github.com/FabricMC/fabric/pull/3799, https://github.com/comp500/Indium/pull/295) arose due to a report of an incompatibility report between the A Good Place mod and Continuity (https://github.com/PepperCode1/Continuity/issues/420), where the A Good Place mod adds animations when placing blocks, but when using any Connected Textures resourcepack the animations present a problem, because the block appears in place before the animation is finished.

https://github.com/FabricMC/fabric/assets/105888751/57b23c47-cd81-42c8-af62-27d1cea2e590



this problem **only** happens when Sodium and Indium are also present, in the video below im not using these mods


https://github.com/FabricMC/fabric/assets/105888751/7e8d46d7-2189-4263-b34d-7065c381234a



I've updated all the mods where the fix has already been implemented (Indium and Fabric API)

Mods links -
https://modrinth.com/mod/a-good-place
https://modrinth.com/mod/continuity
Fabric 1.20.1
Fabric Loader 0.15.11

**Comment by PepperCode1** [comment]
This issue as described by the title and description is definitely 100% fixed, so it does not make sense to discuss unrelated issues here. Use the issue trackers for those mods to report remaining incompatibilities.

**Comment by peow** [comment]
ok, sorry
i only commented here because you said
> Use [FabricMC/fabric#3798](https://github.com/FabricMC/fabric/issues/3798) to track this issue since it's not a Continuity issue.
