### ISSUE TITLE
Release a fabric api fatjar with all the modules shaded

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric#448]
Fabric api has a ton of small modules, which cloud up the dependency view. It would be nice to only have 1 jar in dev.

I’m not sure how this would be implemented technically, there needs to be a way to make this the default with the existing setup.

**Comment by modmuss50** [comment]
Not really possible as there isn’t a way to have multiple mods in one jar.

What’s your usecase as well?

**Comment by natanfudge** [comment]
For one, 
> cloud up the dependency view

Also, this should make it possible to JIJ fabric API.

**Comment by modmuss50** [comment]
JIJing a fat fabric jar is a really really bad idea.

It means loader wont be able to loader possible newer versions supplied by other mods.

**Comment by natanfudge** [comment]
Why not?

**Comment by Player3324** [comment]
JARs (base URLs) are the atomic unit the class loader can (somewhat) easily reorder or prioritize.

I see this requested feature only as a workaround for IDEs being unable to show the module contents nicely, but if you look at how Eclipse shows the modular Java 9+ system library, it is very similar. The main difference is that it uses short names, maybe loom could achieve this by putting version and mapping info in the parent folder name instead of the jar filename after remapping.

**Comment by modmuss50** [comment]
I don't see this happening.
