### ISSUE TITLE
Neither vanilla nor modded tags applied to items

### ISSUE THREAD

**Issue by cppietime** [FabricMC/fabric#670]
When an `acacia_log.json` file is placed under `src/main/resources/data/minecraft/tags/blocks`, with the following contents:

```
{
  "replace": false,
  "values": [
    "minecraft:dirt"
  ]
}
```

Dirt does not register as an acacia log in recipes or when using `clear` in-game. Furthermore, if the same file is placed under `.../data/modid/tags/blocks`, the tag `#modid:acacia_logs` does not exist in-game.

**Comment by JamiesWhiteShirt** [comment]
Probably related to #66

**Comment by cppietime** [comment]
> Probably related to #66

That still appears unsolved, too. And, while perhaps related, I am not confident that they are the same issue.

**Comment by Chocohead** [comment]
I think this comes from a misunderstanding of how the tags are defined rather than a merely a loading problem. If you add a block tag it won't work in recipes as they use item tags. The same way the `/tag` command won't work with a block tag as that uses entity tags. As far as I'm aware you have to explicitly re-state a tag if it has one form but you want to use it for another as they're unique per type rather than globally.

**Comment by i509VCB** [comment]
Seems to be intentional vanilla behavior since item and block tags are two separate constructs, hence they do not share entries.

Closing.
