### ISSUE TITLE
ArmorMaterial identifier is not mod dependent

### ISSUE THREAD

**Issue by Siphalor** [FabricMC/fabric#96]
I just noticed that when registering new armor materials, their name is not an `Identifier`.
This leads to the strange situation that when implementing own armor sets Minecraft will always search `minecraft:textures/models/armor` for their 3d texture.

Shouldn't Fabric API have an interface for this or at least gain the correct namespace by the item's id?

**Comment by asiekierka** [comment]
Parsing the Strings as Identifiers might be easier.

**Comment by Siphalor** [comment]
Is this ever going to be worked on again?
My original pr (#98) was closed with the note that this is being worked on?!

**Comment by modmuss50** [comment]
I dont see why not, sadly I dont know what asie's idea was.

**Comment by i509VCB** [comment]
See #963

**Comment by Juuxel** [comment]
This is still an issue in 1.19. While originally resolved in #963 with the armor texture API, it was never included in the 1.17 branch for some reason. Instead, it got replaced with a new armor rendering registry (#1607) that only lets you do fully custom rendering instead of just providing mod-dependent texture paths.
