### ISSUE TITLE
[1.16.2-pre1] Crash at Mixin Initialization during IDE Launching Minecraft Client

### ISSUE THREAD

**Issue by yuesha-yc** [FabricMC/fabric#989]
Hi I just updated my mappings and fapi and the loader from 1.16.1 to 1.16.2-pre1
```
minecraft_version=1.16.2-pre1
yarn_mappings=1.16.2-pre1+build.17
loader_version=0.9.0+build.204

#Fabric api
fabric_version=0.16.3+build.390-1.16
```

Basically it crashes on launching on some module at Mixin initialization part. 

Runtime stacktrace:
https://paste.ubuntu.com/p/tMWQ9Mcdww/
Latest.log:
https://paste.ubuntu.com/p/xpbx92M6pQ/

Thanks in advance

**Comment by OroArmor** [comment]
I have the same issue. this would be nice to fix

**Comment by i509VCB** [comment]
REI or something else seems to be including `fabric-dimensions` which is not present currently in 1.16.2-pre1. You should exclude fabric api dependency from gradle.

So you would wrap your dependency in brackets like the following:
```
modImplementation(...)  {
    exclude(module: "fabric-api")
}
```

Otherwise mark the dependency as `transitive`. For REI that would make the game fail to start

**Comment by shedaniel** [comment]
The log shows that they are using the 1.16.1 version of REI. Please update.
